const PENDING_SUFFIX = '_PENDING';
const SUCCESS_SUFFIX = '_SUCCESS';
const FAIL_SUFFIX = '_FAIL';

const FETCH_SONG_DETAIL = 'FETCH_SONG_DETAIL';
const FETCH_SONG_LYRICS = 'FETCH_SONG_LYRICS';
const FETCH_SONG_URL = 'FETCH_SONG_URL';


export {
    PENDING_SUFFIX,
    SUCCESS_SUFFIX,
    FAIL_SUFFIX,

    FETCH_SONG_DETAIL,
    FETCH_SONG_LYRICS,
    FETCH_SONG_URL
}