const PENDING_SUFFIX = '_PENDING';
const SUCCESS_SUFFIX = '_SUCCESS';
const FAIL_SUFFIX = '_FAIL';
const FETCH_PERSONALIZED = 'FETCH_PERSONALIZED';
const FETCH_LATEST_MUSIC = 'FETCH_LATEST_MUSIC';
const FETCH_HOT_MUSIC = 'FETCH_HOT_MUSIC';
const FETCH_HOT_SEARCH = 'FETCH_HOT_SEARCH';
const FETCH_SEARCH_HISTORY = 'FETCH_SEARCH_HISTORY';
const FETCH_SEARCH_SUGGEST = 'FETCH_SEARCH_SUGGEST';
const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';

const UPDATE_NAV = 'UPDATE_NAV';
const RECOMMEND = 'recommend';
const HOT = 'hot';
const SEARCH = 'search';

export {
    PENDING_SUFFIX,
    SUCCESS_SUFFIX,
    FAIL_SUFFIX,
    FETCH_PERSONALIZED,
    FETCH_LATEST_MUSIC,
    FETCH_HOT_MUSIC,
    FETCH_HOT_SEARCH,
    FETCH_SEARCH_HISTORY,
    FETCH_SEARCH_SUGGEST,
    FETCH_SEARCH_RESULT,

    UPDATE_NAV,
    RECOMMEND,
    HOT,
    SEARCH
}

